version: '3.7'

services:
  first-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: first-server:latest
    container_name: first-server
    ports:
      - "8082:8082"
    networks:
      - eureka-network
    restart: unless-stopped

networks:
  eureka-network:
    name: eureka-netwrok
    driver: bridge

